use_frameworks!

platform :ios, '10.0'

target 'ScrollViewProvider_Example' do
  pod 'ScrollViewProvider', :path => '../'

  target 'ScrollViewProvider_Tests' do
    inherit! :search_paths

    
  end
end
