use_frameworks!

platform :ios, '13.0'

target 'ScrollViewProvider_Example' do
  
  pod 'ScrollViewProvider/Core', :path => '../'
  pod 'ScrollViewProvider/Refreshable', :path => '../'
  pod 'ScrollViewProvider/Searchable', :path => '../'
  pod 'ScrollViewProvider/Draggable', :path => '../'
  
  pod 'Extension/Array', :path => '../../Extension'

  target 'ScrollViewProvider_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
